### ISSUE TITLE
MajorFault

### ISSUE THREAD

**Issue by brightjdb** [fedtools/adfstoolkit#22]
PS C:\ADFSToolkit\1.0.0.0> .\sync-ADFSTkAggregates.ps1
10/16/2018 2:20:15 PM: Import-ADFSTkMetadata path: C:\ADFSToolkit\1.0.0.0
10/16/2018 2:20:15 PM: Setting SPHashFile to: c:\ADFSToolkit\1.0.0.0\cache\UNC-DEV--SPHashfile.xml
10/16/2018 2:20:15 PM: Setting CachedMetadataFile to: c:\ADFSToolkit\1.0.0.0\cache\UNC-DEV--metadata.cached.xml
10/16/2018 2:20:15 PM: Metadata file size is 926130
Write-ADFSTkVerboseLog : A parameter cannot be found that matches parameter name 'MajorFault'.
At C:\Program Files\WindowsPowerShell\Modules\ADFSToolkit\Private\Verify-ADFSTkSigningCert.ps1:14 char:90
+ ... "Could not convert signingCertString to X509 certificate" -MajorFault
+                                                               ~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Write-ADFSTkVerboseLog], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Write-ADFSTkVerboseLog
![capture](https://user-images.githubusercontent.com/44210054/47038613-e9cdcb80-d14f-11e8-8c36-a64c84fd58c3.PNG)

**Comment by canariecaf** [comment]
Can you attache the metadata file in question? and the fingerprint used to validate it?
What tool did you use to sign it? XMLTools from Shib Consortia?

Thx

**Comment by brightjdb** [comment]
It's a federation with my University System (UNC Federation) I'm with one of 17 schools.  I was able to pull in InCommon no issues.  Also seems that to get passed certain errors you need to open a new PS session (Once in error state always) unless you start over with Sync.  Federation XML http://federation.northcarolina.edu/federation_unc/dev/metadata.xml

I got this from the .pem cert within metadata in shibboleth config folders.
4652A7CB2EF0A2D7BC8A5F0F93C0A1914F8943851D3AA5AF3BC667DC494505C8

Thanks,
Josh

        
        <MetadataProvider id="URLMD_dev"
                          xsi:type="FileBackedHTTPMetadataProvider"
                          backingFile="%{idp.home}/metadata/federation_unc_dev_metadata_backingFile.xml"
                          metadataURL="https://federation.northcarolina.edu/federation_unc/dev/metadata.xml">

            <MetadataFilter xsi:type="SignatureValidation" requireSignedRoot="true" certificateFile="%{idp.home}/conf/metadata/unc_federation.pem"/>

            <MetadataFilter xsi:type="EntityRoleWhiteList">
                <RetainedRole>md:SPSSODescriptor</RetainedRole>
            </MetadataFilter>
        </MetadataProvider>

**Comment by brightjdb** [comment]
Just noticed the UNC Federation Certificate is expired....  Could that be the cause?

**Comment by brightjdb** [comment]
Is there a better way to "Filter" out only SP's I want from a being imported?  I have set it up this way.  If there is a better place to post the questions, please direct me.


#ADFSToolkit: : 10/17/2018 10:33:54

$CurrentLiveVersion = 1.0.0.0

$md=get-module -ListAvailable adfstoolkit; Import-module $md

#Get allowed SP's instead of entire Federation
$EntityIDs = Get-Content 'C:\ADFSToolkit\1.0.0.0\InCommonEntityIDs.txt'

#Loop through list and process
ForEach ($EntityID in $EntityIDs) 
{
Import-ADFSTkMetadata -EntityID $EntityID -ForceUpdate -ConfigFile 'c:\ADFSToolkit\1.0.0.0\config\config.InCommon.xml'
}

#Import-ADFSTkMetadata -ProcessWholeMetadata -ForceUpdate -ConfigFile 'c:\ADFSToolkit\1.0.0.0\config\config.InCommon.xml'

#Updated by: #ADFSToolkit: : 10/17/2018 10:33:54

**Comment by canariecaf** [comment]
Hi.
At this time, no, there is not a formal way to filter things out. You have an intriguing technique to do so though -- nicely done! 
Usually it's an all or nothing (the whole aggregate) but are looking at the ways to do loading of say R&S entity category as a feature request. 

Loading only segments of an aggregate, today, generally means you are doing an incomplete federation story -- ie, you are NOT doing multi-lateral federation, but are only one step away.  It's very MDQ like.

These questions are ok here and if you want a more broad place, you could try Slack on https://edugain.slack.com  'adfs' channel which I am on and the other dev is as well.

Regarding the expired signing cert, that may be very likely as we delegate the crypto assessment to the PS subsystem and it may be complaining about it

**Comment by brightjdb** [comment]
Thanks,

One last question... EPPN looks like the transform rules you guys built
does a regex to replace UPN with global setting for domain at setup.  How
can I stop that? My UPN is what I want,  I have a root wcu.edu and students
@catamount.wcu.edu. So replacing to just the root won’t work for my student
population.

Thanks again!

**Comment by canariecaf** [comment]
Hi Joshua,
(I checked your InCommon idp record to get that)
Right, ADFSToolkit is purpose built for one SAML Scope assignment at this time. To do more is quite tedious and would require quite a bit of refactoring and not in the original scope of the tool.

I'm going to pivot to an operational observation to see if this informs your config:
I'm making a bit of a leap but if you are trying to replace your existing IdP, the scope is a single scope: 'wcu.edu' 
( https://met.refeds.org/met/entity/https%3A//judge.wcu.edu/idp/shibboleth/?viewxml=true&federation=incommon-federation ) 

Given that your production IdP has only one domain, it's not relevant whether they are @wcu.edu, @catamount.wcu.edu, or @wcu.local -- if they are in one AD the left-hand side of the UPN  (Samaccountname@realm) is unique

If you have someone from WCU here at TechEx18, happy to connect.
