### ISSUE TITLE
Error comparing Metadata Hashes

### ISSUE THREAD

**Issue by nebriv** [fedtools/adfstoolkit#27]
Hello,

We've encountered an error during the comparison of our metadata hashes. When doing a manual comparison of these hashes they match. In the error message output they also appear to match... This was working up until August 5th 2019 from what we can tell, we had set it up in April 2019. We've tried removing our configs and the cached metadata but are getting the same error.

This is the error we're getting:

> PS C:\ADFSToolkit\1.0.0.0> .\sync-ADFSTkAggregates.ps1
8/20/2019 1:23:28 PM: Import-ADFSTkMetadata path: C:\ADFSToolkit\1.0.0.0
8/20/2019 1:23:28 PM: Setting SPHashFile to: c:\ADFSToolkit\1.0.0.0\cache\Incomm-SPHashfile.xml
8/20/2019 1:23:28 PM: Setting CachedMetadataFile to: c:\ADFSToolkit\1.0.0.0\cache\Incomm-metadata.cached.xml
8/20/2019 1:23:32 PM: Metadata file size is 63771551
8/20/2019 1:23:32 PM: Comparing aggregate certificate hash of: 2F9D9AA1FED192F064A8C6315D39FACF1E08840D2721F331B170A52B88819F5B to 2F9D9AA1FED192F064A8C6315D39FACF1E08840D2721F331B170A52B88819F5B
Metadata signature test did not pass. Aborting!
At C:\Program Files\WindowsPowerShell\Modules\ADFSToolkit\1.0.0.0\Private\Write-ADFSTkLog.ps1:270 char:28
\+         if ($MajorFault) { throw $Message }
\+                            ~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Metadata signat...pass. Aborting!:String) [], RuntimeException
    + FullyQualifiedErrorId : Metadata signature test did not pass. Aborting!

This is the snippet of our config with the hash and metadata file:
`  <metadataURL>http://md.incommon.org/InCommon/InCommon-metadata.xml</metadataURL>
  <signCertFingerprint>2F9D9AA1FED192F064A8C6315D39FACF1E08840D2721F331B170A52B88819F5B</signCertFingerprint>`

**Comment by nebriv** [comment]
Disregard - we may have identified the issue. Self-inflicted due to a cert change.

**Comment by canariecaf** [comment]
Thanks for the note and reviewing this. @nebriv Appreciate it!

**Comment by nebriv** [comment]
Will update with whatever we find

**Comment by canariecaf** [comment]
Side note: if you have a working MD item (aug 5th as you specify) do a diff on the XML against the following day that doesn't work.  XML signing processes rely on creating a signature ( usually using  pyFF or  [xmlsectool](https://wiki.shibboleth.net/confluence/display/XSTJ2/xmlsectool+V2+Home) that in turn can be validated by independant processes. *SOMETIMES* under the hood some systems strip or don't strip whitespace. XML validation by ADFSToolkit relies on the Microsoft XML validation library -- something out of our control to influence.  The signed metadata is SAML2 compliant however which is the tricky part. Validators of XML and different than XML signature validators -- something one would expect would be the same but sadly are not.

**Comment by nebriv** [comment]
I'm going to re-open this issue for visibility (in case others are having issues) until we fix it.

We ran the VerifyMetadata Function (https://github.com/fedtools/adfstoolkit/blob/760b5840686405e74c49a5128fffaa65e3aee388/ADFSToolkit/Private/Verify-ADFSTkMetadataSignature.ps1) manually against a previous metadata file we had from InCommon. This passes successfully, so its clear its an issue somewhere with the new metadata files or OS functions (built-in validators/etc) or some combination of the two.

We're currently working on diffing the two MD files. Obviously there's quite a few differences with the IDPs and SPs - and the signing signatures are different as a result. We'll look into pyFF/xmlsectool.

**Comment by canariecaf** [comment]
sent ping to your github contact co-ords for more in depth contact info.

**Comment by canariecaf** [comment]
This issue was isolated to the presence of '&#13;' in the metadata where the XML validation in Microsoft's libraries have challenges interpreting it thus failing signature validation.  Once this was eliminated from the aggregate, the validation succeeded.  
Ticket is being closed and is not an ADFSToolkit issue but a data issue which was resolved by data edits.

**Comment by canariecaf** [comment]
ok, for the benefit of search engines -- THIS 5 character string(carriage return expressed as HTML encoding): & # 1 3 ; (remove the spaces to see it -- github strips it's input in the pages) was the problem.  other keywords this may be for discoverability:  ampersand #13; NOW I'll close it :)
