### ISSUE TITLE
RFE: add ability to handle different behaviours for ADFS signed responses and ADFS signed Assertions

### ISSUE THREAD

**Issue by teamktown** [fedtools/adfstoolkit#36]
Some SAML2 services/components have more strict requirements to require  more than just Assertion signing but also message  signing. 
It  would be  well received  to be more flexible.

Such an enhancement would allow ADFSToolkit to:

1.  preserve existing out of the box ADFS behaviour (expected as **AssertionOnly** ) as default
2. Allow  a site  operator to apply a different default such as **MessageAndAssertion** if  desired
3. have the ability  to selectively adjust a given SP whilst leaving other configurations alone  via the ADFSTk-LocalManualSPSettings.ps1 file

REFERENCES: 
3 possible settings of [set-adfsrelyingpartyTrust](https://docs.microsoft.com/en-us/powershell/module/adfs/set-adfsrelyingpartytrust?view=win10-ps) for -SamlResponseSignature which are:

		AssertionOnly
		MessageAndAssertion
		MessageOnly

Technology stack/endpoints that may  require this:
The SATOSA proxy: https://github.com/IdentityPython/SATOSA

**Comment by nckroy** [comment]
FYI I don't think the SATOSA proxy necessarily requires this, it's just that Internet2's deployment of it in our IAM platform does require it, for security reasons (see also: https://www.sso-attacks.org/XML_Signature_Wrapping)

**Comment by canariecaf** [comment]
Closing and resolved in release v2.0.0 https://github.com/fedtools/adfstoolkit/releases/tag/v2.0.0
